export const electionAbi = [
  {
    inputs: [
      { internalType: "address", name: "organizer", type: "address" },
      { internalType: "string", name: "title", type: "string" },
      { internalType: "string[]", name: "positionNames", type: "string[]" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { inputs: [], name: "AlreadyStarted", type: "error" },
  { inputs: [], name: "AlreadyVoted", type: "error" },
  { inputs: [], name: "CandidateAlreadyAdded", type: "error" },
  { inputs: [], name: "ElectionAlreadyEnded", type: "error" },
  { inputs: [], name: "ElectionPaused", type: "error" },
  { inputs: [], name: "EmptyPosition", type: "error" },
  { inputs: [], name: "InvalidBallot", type: "error" },
  { inputs: [], name: "InvalidCandidateIndex", type: "error" },
  { inputs: [], name: "InvalidDuration", type: "error" },
  { inputs: [], name: "InvalidIndex", type: "error" },
  { inputs: [], name: "InvalidOrganizer", type: "error" },
  { inputs: [], name: "InvalidPositionIndex", type: "error" },
  { inputs: [], name: "InvalidWallet", type: "error" },
  { inputs: [], name: "MissingCandidates", type: "error" },
  { inputs: [], name: "NameRequired", type: "error" },
  { inputs: [], name: "NoPositions", type: "error" },
  { inputs: [], name: "NotActive", type: "error" },
  { inputs: [], name: "NotDraft", type: "error" },
  { inputs: [], name: "NotWhitelisted", type: "error" },
  { inputs: [], name: "ReentrancyGuardReentrantCall", type: "error" },
  { inputs: [], name: "TitleRequired", type: "error" },
  { inputs: [], name: "TooEarly", type: "error" },
  { inputs: [], name: "Unauthorized", type: "error" },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "positionIndex", type: "uint256" },
      { indexed: false, internalType: "string", name: "name", type: "string" },
      { indexed: false, internalType: "address", name: "wallet", type: "address" },
    ],
    name: "CandidateAdded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: "uint256", name: "timestamp", type: "uint256" }],
    name: "ElectionEnded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "uint256", name: "startTime", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "endTime", type: "uint256" },
    ],
    name: "ElectionStarted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [],
    name: "Paused",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [],
    name: "Resumed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: "address", name: "voter", type: "address" }],
    name: "VoteCast",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: "address", name: "voter", type: "address" }],
    name: "VoterWhitelisted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: "uint256", name: "count", type: "uint256" }],
    name: "VotersWhitelisted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "positionIndex", type: "uint256" },
      { indexed: true, internalType: "uint256", name: "candidateIndex", type: "uint256" },
      { indexed: false, internalType: "address", name: "wallet", type: "address" },
      { indexed: false, internalType: "string", name: "name", type: "string" },
      { indexed: false, internalType: "uint256", name: "votes", type: "uint256" },
    ],
    name: "WinnerDeclared",
    type: "event",
  },
  {
    inputs: [
      { internalType: "uint256", name: "positionIndex", type: "uint256" },
      { internalType: "string", name: "name", type: "string" },
      { internalType: "address", name: "wallet", type: "address" },
    ],
    name: "addCandidate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address[]", name: "voters", type: "address[]" }],
    name: "whitelistVoters",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "electionStatus",
    outputs: [{ internalType: "enum Election.Status", name: "", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "electionTitle",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "endTime",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "finalizeElection",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "posIndex", type: "uint256" },
      { internalType: "uint256", name: "candIndex", type: "uint256" },
    ],
    name: "getCandidate",
    outputs: [
      { internalType: "string", name: "name", type: "string" },
      { internalType: "address", name: "wallet", type: "address" },
      { internalType: "uint256", name: "votes", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getElectionStats",
    outputs: [
      { internalType: "uint256", name: "_totalVoters", type: "uint256" },
      { internalType: "uint256", name: "_votesCast", type: "uint256" },
      { internalType: "uint256", name: "_startTime", type: "uint256" },
      { internalType: "uint256", name: "_endTime", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "index", type: "uint256" }],
    name: "getPosition",
    outputs: [
      { internalType: "string", name: "title", type: "string" },
      { internalType: "uint256", name: "candidateCount", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getPositionsCount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "voter", type: "address" }],
    name: "getVoterBallot",
    outputs: [{ internalType: "uint256[]", name: "", type: "uint256[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "hasVoted",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "pause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "paused",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "resume",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "durationSeconds", type: "uint256" }],
    name: "startElection",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "startTime",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalVotesCast",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalWhitelistedVoters",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256[]", name: "candidateIndexes", type: "uint256[]" }],
    name: "vote",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "whitelisted",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
] as const;
